### ISSUE TITLE
Error setting up database url

### ISSUE THREAD

**Issue by atilafassina** [xataio/vscode-extension#66]
After the last update for multi-region support the extension is creating and incomplete and invalid URL for the database.

Once clicked on the *Get Started* to link to a database on the *Project* panel, the following dialog pops-up:

![Screenshot 2022-11-11 at 13 11 46](https://user-images.githubusercontent.com/2382552/201349642-e1a53f05-731b-470a-ada3-17293ad3406a.png)

And the generated `.xatarc` has the following value:

```json
{
  "databaseURL": "/db/my-db-name"
}
```

instead of the following pattern:
```
https://{{workspace name}}.{{ region }}.xata.sh/db/{{ db name }}
```

Once properly generated and added, the Extension also throws an error saying the URL is invalid.

**Comment by fabien0102** [comment]
Fixed in 0.4.1
